### ISSUE TITLE
bump to Symfony 7

### ISSUE THREAD

**Issue by tacman** [jolicode/symfony-htmx-demo#3]
Or 6.4, but really Symfony 7.  There were some assetmapper changes between 6.3 and 6.4, too.  No reason to lock this repo at 6.3.

**Comment by Nispeon** [comment]
Indeed I do not think that there is any reason to keep this repo in 6.3, but upgrading to Sf 7 would not change much to this project and I feel it would be a big task with little purpose.

That said, if a PR was opened to take care of it, it'd be my pleasure to merge it 😄
