### ISSUE TITLE
Use Sqlite, skip docker

### ISSUE THREAD

**Issue by tacman** [jolicode/symfony-htmx-demo#5]
Since this application doesn't require any services except a database, we could drop docker altogether if the default dev database was sqlite.

The upside:

* install and run the app with a simple cut-and-paste (git clone, composer install, etc.)
* No database setup.  A database with some messages could be included.

The downside:

* deployment to a production server may not work if the production image is readonly.  

This is how I code most of my small projects, sqlite locally and postgres in production.  Alas, doctrine now complains when I switch to postgres because the AUTO id generates SERIAL instead of SEQUENCE, but Sqlite can't handle SEQUENCE.    Regardless, I can bump the project to 6.4 or 7, but figured I'd address this at the same time.

**Comment by Nispeon** [comment]
Hello, thank you for your suggestion once again!

This repository was made as a simple support for an article, and we used tooling that we are familiar with to make the process faster. While I do agree with your points, this project is not meant to evolve past that initial goal.

Sqlite would indeed be a fine alternative, but we are not interested in changing the database for this application.
I'm going to close this issue, but thanks once again for your suggestion and interest! 😄
