### ISSUE TITLE
Add PWA capabilities, allow demo to run offline

### ISSUE THREAD

**Issue by tacman** [jolicode/symfony-htmx-demo#7]
I've been working a lot with https://github.com/Spomky-Labs/pwa-bundle, and have even submitted a proposal to speak on it at the Symfony Live conference in Berlin in June.

I thought this would be an interesting app to make run offline.  I'm happy to do that.   If you agree, all I'd need is a logo file at least 512x512.

The biggest challenge (for me, at least) will be to set up the "Add Message" so if the site is offline it gets properly queued for background-sync.  Fortunately, the bundle author just added that feature.

Thoughts?

**Comment by Nispeon** [comment]
Hi again,
Thanks for your interest in this repository!

I agree that this is all pretty interesting, and making the app work offline would be a cool feat for sure. 
However the purpose of this repository is mainly to provide a support for [this article](https://jolicode.com/blog/making-a-single-page-application-with-htmx-and-symfony) on our blog.

I fear that adding too much unrealated stuff to it might confuse new readers if were they to try and read the code here to better understand the article, so we do not need a PR on this subject. 

You can however feel free to fork this repository and expand upon it on the side, I'd be very interested to see what you do with it!
