### ISSUE TITLE
rename "new page" to "about"

### ISSUE THREAD

**Issue by tacman** [jolicode/symfony-htmx-demo#8]
To me, "new page" sounds like I can create a new page.

I was thinking an "about" page would be appropriate, with a link to the article, the github repo, and maybe the htmx page.  As such, it's an excellent candidate for caching.

**Comment by Nispeon** [comment]
I would rather keep the new page as it is, so as to not confuse anyone who would be following along [this part of the article](https://jolicode.com/blog/making-a-single-page-application-with-htmx-and-symfony#navigating).

But I like the idea of referencing the article/htmx docs in the code, and adding a whole new "About" page with these links could be interesting, maybe it could even fit in a footer instead. 
Either way, I'd be happy  to merge it if a PR were to be opened 👍🏽
